# Generated by Django 6.0.7 on 2026-07-19 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('income', '0002_income_tax_deduction_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('payment_source', models.CharField(choices=[('usaa', 'USAA'), ('usaa_savings', 'USAA Savings'), ('chase', 'Chase'), ('capone', 'CapOne')], max_length=20)),
                ('payment_type', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], max_length=10)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='income.income')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
