# Generated by Django 6.0.7 on 2026-07-19 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
        ('income', '0002_income_tax_deduction_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='income.income'),
        ),
    ]
