# Generated by Django 6.0.7 on 2026-07-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_alter_bill_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
