# Generated by Django 6.0.7 on 2026-07-19 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_bill_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_recurring',
            field=models.BooleanField(default=True, help_text='Repeats monthly on the same day. Uncheck for a one-time bill.'),
        ),
        migrations.AddField(
            model_name='bill',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Optional. Recurring bill stops after this date (e.g. final loan payment).', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(help_text='First/anchor due date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=False, help_text='Used only for one-time (non-recurring) bills'),
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.bill')),
            ],
            options={
                'unique_together': {('bill', 'year', 'month')},
            },
        ),
    ]
