# Generated by Django 6.0.7 on 2026-07-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='tax_deduction_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
