# Generated by Django 6.0.7 on 2026-07-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_income_tax_deduction_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('semimonthly', 'Semi-Monthly'), ('monthly', 'Monthly'), ('onetime', 'One-Time')], max_length=12),
        ),
    ]
